### ISSUE TITLE
java.lang.NoSuchMethodError: io.netty.util.concurrent.SingleThreadEventExecutor

### ISSUE THREAD

**Issue by pachi009** [Azure/azure-functions-java-library#133]
17:38:01.399 [ForkJoinPool.commonPool-worker-9] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
java.lang.NoSuchMethodError: io.netty.util.concurrent.SingleThreadEventExecutor.<init>(Lio/netty/util/concurrent/EventExecutorGroup;Ljava/util/concurrent/Executor;ZLjava/util/Queue;Lio/netty/util/concurrent/RejectedExecutionHandler;)V
        at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:65) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:138) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:138) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-common-4.1.17.Final.jar:4.1.17.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[netty-common-4.1.17.Final.jar:4.1.17.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[netty-common-4.1.17.Final.jar:4.1.17.Final]
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:78) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:73) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:60) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
        at reactor.netty.resources.DefaultLoopResources.cacheNioServerLoops(DefaultLoopResources.java:172) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.resources.DefaultLoopResources.cacheNioClientLoops(DefaultLoopResources.java:192) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.resources.DefaultLoopResources.onClient(DefaultLoopResources.java:186) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.tcp.TcpResources.onClient(TcpResources.java:179) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.http.client.HttpClientConnect$HttpTcpClient.connect(HttpClientConnect.java:134) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.tcp.TcpClient.connect(TcpClient.java:187) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.http.client.HttpClientFinalizer.connect(HttpClientFinalizer.java:68) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:85) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at com.azure.core.http.netty.NettyAsyncHttpClient.send(NettyAsyncHttpClient.java:70) ~[azure-core-http-netty-1.2.0.jar:?]
        at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:44) ~[azure-core-1.2.0.jar:?]
        at com.azure.storage.common.policy.ScrubEtagPolicy.process(ScrubEtagPolicy.java:35) ~[azure-storage-common-12.2.0.jar:?]
        at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46) ~[azure-core-1.2.0.jar:?]
        at com.azure.core.http.policy.HttpLoggingPolicy.process(HttpLoggingPolicy.java:84) ~[azure-core-1.2.0.jar:?]
        at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46) ~[azure-core-1.2.0.jar:?]
        at com.azure.storage.common.policy.ResponseValidationPolicyBuilder$ResponseValidationPolicy.process(ResponseValidationPolicyBuilder.java:77) ~[azure-storage-common-12.2.0.jar:?]
        at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46) ~[azure-core-1.2.0.jar:?]
        at com.azure.storage.common.policy.RequestRetryPolicy.attemptAsync(RequestRetryPolicy.java:114) ~[azure-storage-common-12.2.0.jar:?]
        at com.azure.storage.common.policy.RequestRetryPolicy.process(RequestRetryPolicy.java:48) ~[azure-storage-common-12.2.0.jar:?]
        at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46) ~[azure-core-1.2.0.jar:?]
        at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.lambda$process$1(BearerTokenAuthenticationPolicy.java:51) ~[azure-core-1.2.0.jar:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:495) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:495) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:86) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_261]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_261]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_261]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_261]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_261]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_261]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_261]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_261]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) [?:1.8.0_261]

Dependencies used are 
<dependency>
        	<groupId>com.microsoft.azure</groupId>
        	<artifactId>azure-storage</artifactId>
        	<version>8.0.0</version>
        </dependency>
        <dependency>
        	<groupId>com.azure</groupId>
        	<artifactId>azure-storage-blob</artifactId>
        	<version>12.2.0</version>
        </dependency>
        <dependency>
        	<groupId>com.azure</groupId>
        	<artifactId>azure-identity</artifactId>
        	<version>1.0.2</version>
        </dependency>

**Comment by amamounelsayed** [comment]
Can you please check https://github.com/Azure/azure-functions-java-worker/issues/381? Thank you!
